FROM php:7.3-apache
RUN apt-get update                                              \
    && apt-get install -y --no-install-recommends git zip       \
    && docker-php-ext-install mysqli pdo pdo_mysql              \
    && a2enmod rewrite                                          \
    && chmod 777 -R -c /var/www

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

# python
# FROM python:3 RUN sudo apt-get install python

# node

# RUN apt-get install git-core curl build-essential openssl libssl-dev  \
    # && git clone https://github.com/nodejs/node.git                   \
    # && cd node                                                        \
    # && ./configure                                                    \
    # && make                                                           \
    # && sudo make install