version: "3.7"
services:
  database:
    build:
      context: ./database
      dockerfile: db.dockerfile
    container_name: web_database
    enviroment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_chalan
      MYSQL_USER: eaf
      MYSQL_PASSWORD: eaf123
    ports:
      - 33069:3306
    volumes:
      - E:\projects\docker\databases\mysql_3.7:/var/lib/mysql
    networks: 
      laravel_prod_net:
        ipv4_address: 172.22.100.9
  backend:
    build:
      context: ./api
      dockerfile: api.dockerfile
    container_name: web_backend
    depends_on:
      - database
    ports:
      - 8200:80
    volumes:
      - E:\projects\prj_elchalanaruba:/var/www/
      - E:\projects\prj_elchalanaruba\the_public:/var/www/html      
    networks: 
      laravel_prod_net:
        ipv4_address: 172.22.100.10

networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.22.100.0/24
