version: "3"
services: 
  wordpress:
    image: wordpress
    environment: 
      WORDPRESS_DB_HOST: dbserver:3306
      WORDPRESS_DB_PASSWORD: mysqlpw
    ports:
      - 80:80
    depends_on: 
      - dbserver

dbserver:
  image: mysql:5.7
  environment: 
    MYSQL_ROOT_PASSWORD: mysqlpw
  ports:
    - 3306:3306